### ISSUE TITLE
Middleware throws TypeError under Django 1.10.4 and Python 3.5.2

### ISSUE THREAD

**Issue by darkpixel** [carljm/django-secure#36]
```
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f5d731ed840>
Traceback (most recent call last):
  File "/home/aaron/.virtualenvs/intranet/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/aaron/.virtualenvs/intranet/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 142, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/aaron/.virtualenvs/intranet/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/home/aaron/.virtualenvs/intranet/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/home/aaron/.virtualenvs/intranet/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/aaron/.virtualenvs/intranet/lib/python3.5/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/home/aaron/.virtualenvs/intranet/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tank/code/intranet/intranet/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/home/aaron/.virtualenvs/intranet/lib/python3.5/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/aaron/.virtualenvs/intranet/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
    self.load_middleware()
  File "/home/aaron/.virtualenvs/intranet/lib/python3.5/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: __init__() takes 1 positional argument but 2 were given
```

Removing ```'debug_toolbar.middleware.DebugToolbarMiddleware',``` from ```MIDDLEWARE``` fixes the problem but obviously leaves the site unprotected.

**Comment by carljm** [comment]
The django-secure middleware doesn't support new-style `MIDDLEWARE` setting in Django 1.10, and it never will, because django-secure has been merged into Django core starting with 1.8, and the third-party package is now unsupported and unmaintained and should not be used with Django 1.8+. This is noted clearly at the top of the docs (http://django-secure.readthedocs.io/en/latest/) as well as in the README and in the GitHub project description.

Also, the last line of your bug report mentions `DebugToolbarMiddleware`, which is doubly confusing, since `DebugToolbarMiddleware` has nothing to do with django-secure. Either that was a typo and you meant `django_secure.SecurityMiddleware`, or perhaps you meant to file this report against django-debug-toolbar.
